siderolabs/talos-cloud-controller-manager

- charts/talos-cloud-controller-manager/templates/role.yaml
- charts/talos-cloud-controller-manager/values.yaml
- docs/deploy/cloud-controller-manager.yml
CCM has to have tolerations against uninitialized nodes.
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> fix: uninitialized tolerations

- .dockerignore
- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
- .github/workflows/conform.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- charts/talos-cloud-controller-manager/values-tests.yaml
- hack/CHANGELOG.tpl.md
- hack/chglog-config.yml
- hack/ct.yml
GH-Actions:
* build and lint
* helm chart linter
* push release images
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> Gitops automatization

- CHANGELOG.md
- docs/deploy/cloud-controller-manager.yml
> chore: release v1.3.0

- README.md
- charts/talos-cloud-controller-manager/templates/configmap.yaml
- charts/talos-cloud-controller-manager/templates/deployment.yaml
- charts/talos-cloud-controller-manager/templates/serviceaccount.yaml
- docs/deploy/cloud-controller-manager.yml
Add the namespace to all helm-chart resources.
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> fix: helm chart namespace

- pkg/talos/instances.go
Always check/update the node IPs because the network IP may change after node eviction, especially in the case of spot instances.
> fix: node spec ip

- .github/workflows/build-edge.yaml
- Makefile
Build and push the latest edge version to the registry.
> feat: build latest version

- README.md
Update readme.
Add copy past kubectl command tox deploy latest stable version.
> docs: edge deploy with csr

- .github/workflows/release-pre.yaml
- CHANGELOG.md
- README.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
- hack/CHANGELOG.tpl.md
- hack/chglog-config.yml
> Release 1.4.0

- .github/dependabot.yml
- .github/workflows/build-edge.yaml
- .github/workflows/charts.yaml
- .github/workflows/release-charts.yaml
- Makefile
- README.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- docs/cosign.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
Helm chart and image signed by Cosign.
Now you can verify that images were built GitHub Actions.
> feat: sign images

- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
Update actions/checkout, actions/setup-go.
> chore: bump github actions deps

- pkg/talos/client.go
- pkg/talos/cloud.go
- pkg/talos/instances.go
Due to the failover process, we also need to refresh the Talos token.
> fix: refresh talos token

- docs/metrics.md
- pkg/metrics/metrics_trans.go
- pkg/talos/helper.go
- pkg/talos/instances.go
- pkg/transformer/functions.go
- pkg/transformer/transformer.go
- pkg/transformer/transformer_test.go
Add functions to template executer.
> feat: transformer functions

- .github/workflows/build-test.yaml
- pkg/transformer/transformer.go
- pkg/transformer/transformer_test.go
> fix: empty terms

- charts/talos-cloud-controller-manager/templates/deployment.yaml
- charts/talos-cloud-controller-manager/values.yaml
Set missing priorityClassName
It's missing
make conformance error:
```
Error: failed to convert declarations: failed to convert commit policy: 1 error(s) decoding:
* 'gpg' expected a map, got 'bool'
```
> fix: set priorityClassName

- cmd/talos-cloud-controller-manager/main.go
- go.mod
- go.sum
- pkg/talos/instances.go
Remove node kubernetes resource on spot node eviction event.
close #179 
> feat: gcp spot instances

- README.md
- docs/controllers.md
- docs/install.md
Update installation instructions.
Add controllers explanations.
> docs: split readme file

- Makefile
- README.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- charts/talos-cloud-controller-manager/values-example.yaml
- charts/talos-cloud-controller-manager/values.yaml
- docs/config.md
- docs/controllers.md
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/install.md
- pkg/talos/cloud_config.go
- pkg/talos/cloud_config_test.go
Add example of deployment.
Clean up unused params.
> docs: update deploy documentation

- CHANGELOG.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- charts/talos-cloud-controller-manager/README.md.gotmpl
- charts/talos-cloud-controller-manager/values.yaml
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v1.8.0

- CHANGELOG.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- charts/talos-cloud-controller-manager/values.yaml
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v1.8.1

- docs/config.md
- hack/ccm-config.yaml
- pkg/talos/helper_test.go
- pkg/talos/instances.go
- pkg/talosclient/client.go
- pkg/transformer/functions.go
- pkg/transformer/transformer.go
- pkg/transformer/transformer_test.go
Add SystemInformation resource values to transformer templater.
#232
> feat: add system information for transformer

- .github/workflows/build-edge.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/release.yaml
- go.mod
- go.sum
> chore: bump deps

- CHANGELOG.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v1.9.1

- CHANGELOG.md
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v1.10.0

- .conform.yaml
- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset-edge.yml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-edge.yml
- docs/deploy/cloud-controller-manager.yml
> fix(chart): version type

- charts/talos-cloud-controller-manager/Chart.yaml
- charts/talos-cloud-controller-manager/README.md
We removed this requirement to avoid checking the kubeapi version.
https://github.com/siderolabs/talos-cloud-controller-manager/issues/278
> fix(chart): remove kubernetes version
